# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build 
      working-directory:  'my-app'

    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_LOGIN }}
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: 'manmeera'
        package: 'my-app/dist'
        
    
  
