name: Manmeera CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    # - name: Azure Login
    #   uses: Azure/login@v2
    #   with:
    #     creds: ${{ secrets.AZURE_LOGIN }}

    - name: Azure CLI Action
      uses: Azure/cli@v2.0.0
      with:
    
        inlineScript: az login \
                      --service-principal \
                      -t 39bb0b44-488e-4fdd-b4e3-27557a7d3f89 \
                      -u 5c95b4b6-7bc9-4a27-aa89-39011d0e865b \
                      -p Mt18Q~pX8j2tLj_W464VsWA~NdzLrjzizMOL.dat
   
    - run: npm ci

    - run: npm run build 

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: 'manmeera'
        package: './dist'
