name: Manmeera CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Azure login
      run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.SECRET_ID }} --tenant ${{ secrets.TENANT_ID }}

    - run: npm ci

    - run: npm run build

    - name: List Build Directory
      run: ls -la ./dist

    - name: List Working Directory
      run: ls -la

    - name: Deploy to Azure WebApp
      run: az webapp deploy --resource-group your-actual-resource-group --name manmeera --src-path dist
