# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Manmeera CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Azure Login
      uses: Azure/login@v2.1.0
      with:
        client-id: '5c95b4b6-7bc9-4a27-aa89-39011d0e865b'
        tenant-id: '39bb0b44-488e-4fdd-b4e3-27557a7d3f89'
        subscription-id: '7988383d-5947-4e42-bede-64c7eb8aa983'
        auth-type: 'SERVICE_PRINCIPAL'
          
    
    - run: npm ci
    - run: npm run build 

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: 'manmeera'
        package: './dist'
        
    
  
