name: Manmeera CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Azure login
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: az login --service-principal -t ${{ secrets.TENANT_ID }} -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.SECRET_ID }}
                      
    - run: npm ci

    - run: npm run build

    - name: List Build Directory
      run: ls -la ./dist

    - name: Deploy to Azure WebApp
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: 'manmeera'
        package: './dist'
